### ISSUE TITLE
Unable to build on OSX - macosx(10.6, 10.12)

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1031]
Author: cminion (cminion)
Date: 2017-04-28
Redmine Issue: 1031, https://dev.etlegacy.com/issues/1031

---

Hi Guys

Happy for this to be my issue.

I am trying to compile on OSX with the master from git.

When I do the make command I get the following error. 

Chriss-MBP-2:etlegacy chris$ cd build/
Chriss-MBP-2:build chris$ make
[  1%] Built target bundled_lua
[  2%] Built target bundled_sqlite3
[  3%] Building CXX object CMakeFiles/qagame_mac.dir/src/game/g_etbot_interface.cpp.o
clang: warning: no such sysroot directory: '-m32' [-Wmissing-sysroot]
/Users/chris/src/etlegacyClient/etlegacy/src/game/g_etbot_interface.cpp:33:10: fatal error: 'sstream' file not found
#include <sstream>

I have installed the prereqs listed, and xcode is loaded. What am i doing wrong?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-04-29T04:05:59Z

---

OB doesn't support OSX. Set FEATURE_OMNIBOT=0 and INSTALL_OMNIBOT=0.

**Comment by ETLegacyTeam** [comment]
From: cminion (cminion)
Date: 2017-04-29T20:06:15Z

---

IR4T4 wrote:
> OB doesn't support OSX. Set FEATURE_OMNIBOT=0 and INSTALL_OMNIBOT=0.


Thanks that got me further I am now seeing


[ 25%] Building C object CMakeFiles/etlded.dir/src/botlib/l_memory.c.o
[ 25%] Building C object CMakeFiles/etlded.dir/src/botlib/l_precomp.c.o
[ 25%] Building C object CMakeFiles/etlded.dir/src/botlib/l_script.c.o
[ 25%] Building C object CMakeFiles/etlded.dir/src/sys/sys_main.c.o
In file included from /usr/include/Availability.h:190:0,
                 from /usr/include/sys/signal.h:74,
                 from /usr/include/signal.h:63,
                 from /Users/chris/src/etlegacyClient/etlegacy/src/sys/sys_main.c:35:
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFDateFormatter.h:53:34: error: 'introduced' undeclared here (not in a function)
     kCFISO8601DateFormatWithYear API_AVAILABLE(macosx(10.12), ios(10.0), watchos(3.0), tvos(10.0)) = (1UL << 0),
                                  ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:777:39: error: 'deprecated' undeclared here (not in a function)
 const CFStringRef kCFURLLabelColorKey API_DEPRECATED("Use NSURLLabelColorKey", macosx(10.6, 10.12), ios(4.0, 10.0), watchos(2.0, 3.0), tvos(9.0, 10.0));
                                       ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:777:39: error: 'message' undeclared here (not in a function)
 const CFStringRef kCFURLLabelColorKey API_DEPRECATED("Use NSURLLabelColorKey", macosx(10.6, 10.12), ios(4.0, 10.0), watchos(2.0, 3.0), tvos(9.0, 10.0));
                                       ^
make[2]: *** [CMakeFiles/etlded.dir/src/sys/sys_main.c.o] Error 1
make[1]: *** [CMakeFiles/etlded.dir/all] Error 2
make: *** [all] Error 2
Exiting!

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-10-15T13:34:20Z

---

ETL on OSX 10.6 isn't supported and we can't reproduce the above issues with our systems (10.7). OSX is very special. I'll close this.
